import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ur';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations object
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.inventory': 'Inventory',
    'nav.pestControl': 'Pest Control',
    'nav.weather': 'Weather',
    'nav.market': 'Market Prices',
    'nav.education': 'Education',
    'nav.aiInsights': 'AI Insights',
    'nav.farms': 'Farms',
    'nav.contact': 'Contact Us',
    
    // Weather
    'weather.title': 'Weather Forecast',
    'weather.searchPlaceholder': 'Enter city name...',
    'weather.search': 'Search',
    'weather.searchPrompt': 'Enter a city name to get weather information',
    'weather.temperature': 'Temperature',
    'weather.feelsLike': 'Feels Like',
    'weather.humidity': 'Humidity',
    'weather.windSpeed': 'Wind Speed',
    'weather.details': 'Weather Details',
    'weather.condition': 'Condition',
    'weather.pressure': 'Pressure',
    'weather.visibility': 'Visibility',
    'weather.days.today': 'Today',
    'weather.days.tomorrow': 'Tomorrow',
    'weather.days.wednesday': 'Wednesday',
    'weather.days.thursday': 'Thursday',
    'weather.conditions.sunny': 'Sunny',
    'weather.conditions.cloudy': 'Cloudy',
    'weather.conditions.rain': 'Rain',
    'weather.conditions.windy': 'Windy',
    
    // Market Prices
    'market.title': 'Market Prices',
    'market.todaysPrices': "Today's Prices",
    'market.crops.wheat': 'Wheat',
    'market.crops.rice': 'Rice',
    'market.crops.corn': 'Corn',
    'market.crops.soybeans': 'Soybeans',
    'market.regionTitle': 'Region-Specific Crop Market Data',
    'market.region.southasia': 'South Asia',
    'market.region.northamerica': 'North America',
    'market.region.africa': 'Africa',
    'market.region.europe': 'Europe',
    'market.region.southamerica': 'South America',
    'market.region.australia': 'Australia',
    'market.region.eastasia': 'East Asia',
    'market.region.middleeast': 'Middle East',
    'market.loading': 'Loading...',
    'market.error': 'Could not load crop data.',
    'market.cropIndexTable': 'Crop Index Table',
    'market.crop': 'Crop',
    'market.type': 'Type',
    'market.price': 'Price',
    'market.trend': 'Trend',
    'market.change': 'Change',
    'market.cropName.rice': 'Rice',
    'market.cropName.wheat': 'Wheat',
    'market.cropName.sugarcane': 'Sugarcane',
    'market.cropName.cotton': 'Cotton',
    'market.cropName.maize': 'Maize',
    'market.cropName.millets': 'Millets',
    'market.cropName.pulses': 'Pulses',
    'market.cropName.tea': 'Tea',
    'market.cropName.jute': 'Jute',
    'market.cropName.barley': 'Barley',
    'market.cropType.grain': 'Grain',
    'market.cropType.cashcrop': 'Cash Crop',
    'market.cropType.fiber': 'Fiber',
    'market.cropType.legume': 'Legume',
    'market.cropType.beverage': 'Beverage',
    'market.trend.up': 'Up',
    'market.trend.down': 'Down',
    'market.topCropsDistribution': 'Top 10 Crops Distribution',
    'market.farmSuggestions': 'Farm Suggestions',
    'market.suggestion.0': 'Rotate rice and wheat to maintain soil fertility.',
    'market.suggestion.1': 'Monitor for pests during the monsoon season.',
    'market.suggestion.2': 'Consider drip irrigation for sugarcane fields.',
    'market.infoDisclaimer1': 'This information is',
    'market.infoDisclaimer2': 'AI-generated',
    'market.infoDisclaimer3': 'and for guidance only. Not real-time market data.',
    
    // Inventory
    'inventory.title': 'Pesticide Inventory',
    'inventory.addNewItem': 'Add New Item',
    'inventory.searchPlaceholder': 'Search inventory...',
    'inventory.name': 'Name',
    'inventory.quantity': 'Quantity',
    'inventory.category': 'Category',
    'inventory.expiryDate': 'Expiry Date',
    'inventory.actions': 'Actions',
    'inventory.unit': 'Unit',
    'inventory.cancel': 'Cancel',
    'inventory.addItem': 'Add Item',
    'inventory.categories.organic': 'Organic',
    'inventory.categories.chemical': 'Chemical',
    'inventory.units.liters': 'liters',
    'inventory.units.kg': 'kg',
    'inventory.units.units': 'units',
    'inventory.supplier': 'Supplier',
    'inventory.purchaseDate': 'Purchase Date',
    'inventory.notes': 'Notes',
    'inventory.editItem': 'Edit Item',
    'inventory.updateItem': 'Update Item',
    'inventory.deleteItem': 'Delete Item',
    'inventory.delete': 'Delete',
    'inventory.deleteConfirmation': 'Are you sure you want to delete {{name}}?',
    'inventory.lowStockAlert': 'Low Stock Alert',
    'inventory.lowStockItems': '{{count}} items are running low on stock',
    'inventory.expiringAlert': 'Expiring Items Alert',
    'inventory.expiringItems': '{{count}} items are approaching expiry',
    'inventory.totalItems': 'Total Items',
    'inventory.organicItems': 'Organic Items',
    'inventory.chemicalItems': 'Chemical Items',
    
    // Education
    'education.title': 'Education & Resources',
    'education.articlesGuides': 'Articles & Guides',
    'education.videosTutorials': 'Videos & Tutorials',
    'education.regulatoryUpdates': 'Regulatory Updates',
    'education.tipsFarming': 'Tips for Better Farming',
    'education.faqsHelp': 'FAQs & Help Topics',
    'education.pdfDownloads': 'PDF Downloads / Booklets',
    'education.glossary': 'Glossary / Terminology',
    'education.article.0': 'Safe pesticide handling and storage',
    'education.article.1': 'How to choose the right pesticide',
    'education.article.2': 'Effects of overuse and misuse of pesticides',
    'education.article.3': 'Organic and eco-friendly alternatives',
    'education.article.4': 'Government regulations and legal use',
    'education.video.0': 'How-to: Safe Pesticide Application',
    'education.video.1': 'Crop-specific pest control methods',
    'education.video.2': 'Equipment cleaning and maintenance',
    'education.video.3': 'Real farmer experiences',
    'education.tip.0': 'Always read and follow the label instructions on pesticides.',
    'education.tip.1': 'Rotate pesticides to prevent resistance in pests.',
    'education.tip.2': 'Use personal protective equipment (PPE) when handling chemicals.',
    'education.tip.3': 'Spray in the early morning or late afternoon to avoid harming pollinators.',
    'education.tip.4': 'Keep a record of all pesticide applications for future reference.',
    'education.tip.5': 'Store pesticides in a cool, dry, and locked place away from children and animals.',
    'education.tip.6': 'Use integrated pest management (IPM) practices to reduce chemical use.',
    'education.tip.7': 'Clean equipment thoroughly after each use to prevent cross-contamination.',
    'education.faq.0.q': 'What should I do if I spill pesticide on my skin?',
    'education.faq.0.a': 'Remove contaminated clothing and wash skin thoroughly with soap and water. Seek medical attention if irritation persists.',
    'education.faq.1.q': 'How do I know if a pesticide is safe for my crop?',
    'education.faq.1.a': 'Check the label for approved crops and consult local agricultural extension services.',
    'education.faq.2.q': 'What is the re-entry interval (REI)?',
    'education.faq.2.a': 'The REI is the minimum time that must pass before people can re-enter a field after pesticide application.',
    'education.faq.3.q': 'What to do if crop burns after spraying?',
    'education.faq.3.a': 'Stop using the product, irrigate the field if possible, and consult an expert for further advice.',
    'education.glossary.0.term': 'Herbicide',
    'education.glossary.0.def': 'A chemical for killing weeds.',
    'education.glossary.1.term': 'Fungicide',
    'education.glossary.1.def': 'A chemical for controlling fungal diseases.',
    'education.glossary.2.term': 'Residual effect',
    'education.glossary.2.def': 'How long a pesticide remains active after application.',
    'education.glossary.3.term': 'IPM',
    'education.glossary.3.def': 'Integrated Pest Management, a holistic approach to pest control.',
    'education.glossary.4.term': 'REI',
    'education.glossary.4.def': 'Re-entry Interval, the time before people can re-enter a treated area.',
    'education.regulation.0': 'New rules from agriculture departments',
    'education.regulation.1': 'Banned pesticides in Pakistan (2024)',
    'education.regulation.1.detail.0': 'Aldrin',
    'education.regulation.1.detail.1': 'Chlordane',
    'education.regulation.1.detail.2': 'DDT',
    'education.regulation.1.detail.3': 'Dieldrin',
    'education.regulation.1.detail.4': 'Endrin',
    'education.regulation.1.detail.5': 'Heptachlor',
    'education.regulation.1.detail.6': 'Lindane',
    'education.regulation.1.detail.7': 'Mirex',
    'education.regulation.1.detail.8': 'Toxaphene',
    'education.regulation.2': 'Approved pesticides (2024)',
    'education.regulation.2.detail.0': 'Imidacloprid',
    'education.regulation.2.detail.1': 'Lambda-cyhalothrin',
    'education.regulation.2.detail.2': 'Carbendazim',
    'education.regulation.2.detail.3': 'Mancozeb',
    'education.regulation.2.detail.4': 'Glyphosate',
    'education.pdf.0': 'Pesticide usage chart by crop type',
    'education.pdf.1': 'Weather-wise spraying schedules',
    'education.pdf.2': 'Disease identification and treatment manual',
    
    // Pest Control
    'pestControl.title': 'Pest Control Management',
    'pestControl.currentThreats': 'Current Threats',
    'pestControl.aphidsDetected': 'Aphids Detected',
    'pestControl.highRiskSectorA': 'High risk in Sector A',
    'pestControl.takeAction': 'Take Action',
    'pestControl.protectedAreas': 'Protected Areas',
    'pestControl.sectorB': 'Sector B',
    'pestControl.treatmentSuccess': 'Treatment applied successfully',
    
    // AI Dashboard
    'ai.title': 'AI Insights Dashboard',
    'ai.pestDetection': 'Pest Detection',
    'ai.yieldPrediction': 'Yield Prediction',
    'ai.weatherAnalysis': 'Weather Analysis',
    'ai.marketPrediction': 'Market Price Prediction',
    'ai.uploadImage': 'Upload Image',
    'ai.detectedPests': 'Detected Pests',
    'ai.confidence': 'Confidence',
    'ai.loading': 'Loading...',
    
    // Common
    'common.historical': 'Historical',
    'common.predicted': 'Predicted',
    'common.farmer': 'Farmer John',
    'common.viewProfile': 'View Profile',
    'common.temperature': 'Temperature',
    'common.humidity': 'Humidity',
    'common.windSpeed': 'Wind Speed',
    'common.soilMoisture': 'Soil Moisture',
    'common.alerts': 'Recent Alerts',
    'common.farmHealth': 'Farm Health Overview',
    'common.cropHealth': 'Crop Health Index',
    'common.pestRisk': 'Pest Risk',
    'common.waterUsage': 'Water Usage',
    'common.soilQuality': 'Soil Quality',
    'login.title': 'Sign in to your account',
    'login.subtitle': 'Welcome back! Please enter your details.',
    'login.email': 'Email address',
    'login.emailPlaceholder': 'Email address',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Password',
    'login.button': 'Sign in',
    'register.title': 'Create your account',
    'register.subtitle': 'Join us and start your journey!',
    'register.name': 'Full Name',
    'register.namePlaceholder': 'Full Name',
    'register.email': 'Email address',
    'register.emailPlaceholder': 'Email address',
    'register.password': 'Password',
    'register.passwordPlaceholder': 'Password',
    'register.button': 'Register',
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': "Monitor and manage your farm's health",
    'dashboard.lastUpdated': 'Last updated: 5 mins ago',
    'dashboard.activities': 'Farm Activities',
    'dashboard.addActivity': 'Add Activity',
    'dashboard.sortByDate': 'Sort by Date',
    'dashboard.sortByPriority': 'Sort by Priority',
    'dashboard.sortByStatus': 'Sort by Status',
    'dashboard.allActivities': 'All Activities',
    'dashboard.pendingActivities': 'Pending Activities',
    'dashboard.completedActivities': 'Completed Activities',
    'dashboard.allTypes': 'All Types',
    'dashboard.tasks': 'Tasks',
    'dashboard.recommendations': 'Recommendations',
    'dashboard.activityTitle': 'Activity Title',
    'dashboard.activityDescription': 'Activity Description',
    'dashboard.task': 'Task',
    'dashboard.recommendation': 'Recommendation',
    'dashboard.lowPriority': 'Low Priority',
    'dashboard.mediumPriority': 'Medium Priority',
    'dashboard.highPriority': 'High Priority',
    'dashboard.dueDate': 'Due Date',
    'dashboard.cancel': 'Cancel',
    'dashboard.updateActivity': 'Update Activity',
    'dashboard.priorityLow': 'Low Priority',
    'dashboard.priorityMedium': 'Medium Priority',
    'dashboard.priorityHigh': 'High Priority',
    'dashboard.due': 'Due',
    'dashboard.editActivity': 'Edit Activity',
    'dashboard.deleteActivity': 'Delete Activity',
    'dashboard.taskSoilTesting': 'Soil Testing Required',
    'dashboard.descSoilTesting': 'Conduct soil testing in the north field to check nutrient levels and pH balance',
    'dashboard.taskIrrigation': 'Irrigation System Maintenance',
    'dashboard.descIrrigation': 'Inspect and maintain irrigation system in the south field, check for leaks and pressure issues',
    'dashboard.taskCropRotation': 'Crop Rotation Recommendation',
    'dashboard.descCropRotation': 'Based on soil analysis, consider rotating crops in the east field to improve soil health',
    'farm.editFarm': 'Edit Farm',
    'farm.deleteFarm': 'Delete Farm',
    'farm.size': 'Size',
    'farm.acres': 'acres',
    'farm.activities': 'Activities',
    'farm.pesticideUsage': 'Pesticide Usage',
    'farm.totalUsed': 'Total Used',
    'farm.lastUsed': 'Last Used',
    'farm.addActivity': 'Add Activity',
    'farm.area': 'Area',
    'farm.good': 'Good',
    'farm.health': 'Health',
    'farm.watered': 'Watered',
    'farm.pending': 'Pending',
    'farm.needsWater': 'Needs Water',
    'farm.recentActivities': 'Recent Activities',
    'farm.pesticidesList': 'Pesticides List',
    'crops.wheat': 'Wheat',
    'crops.cotton': 'Cotton',
    'crops.tomato': 'Tomato',
    // Contact Us
    'contact.heading': 'Contact Us',
    'contact.subheading': "We'd love to hear from you! Fill out the form below and our team will get back to you soon.",
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Your Name',
    'contact.email': 'Email',
    'contact.emailPlaceholder': 'Your Email',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Type your message...',
    'contact.sendButton': 'Send Message',
    'contact.orReachUs': 'Or reach us at:',
    'contact.address': '123 Green Valley, Farm City, Country',
    'contact.linkedin': 'LinkedIn',
    'contact.facebook': 'Facebook',
    'contact.twitter': 'Twitter',
    'contact.instagram': 'Instagram',
    // Sidebar
    'sidebar.logo': 'AgroAI',
    'sidebar.logout': 'Logout',
    'sidebar.urdu': 'اردو',
    'sidebar.english': 'English',
    // Navbar
    'navbar.logo': 'AgroAI',
    // WeatherForecast additions
    'weather.searchFarmPlaceholder': 'Search farm by name, city, or area...',
    'weather.noFarmsFound': 'No Farms Found',
    'weather.addFarmsPrompt': 'Add farms to show weather data.',
    'weather.rain': 'Rain',
    'weather.frostRisk': 'Frost risk',
    'weather.hailstorm': 'Hailstorm',
    'weather.risks': 'Risks',
    'weather.risk.flooding': 'Flooding',
    'weather.risk.drought': 'Drought',
    'weather.risk.cropdamagefromfrost': 'Crop damage from frost',
    'weather.risk.cropdamagefromheatwave': 'Crop damage from heatwave',
    'weather.risk.lodging/structuredamage': 'Lodging/structure damage',
    'weather.risk.diseasespread': 'Disease spread',
    'weather.alert.rain>50mm': 'Heavy rain',
    'weather.alert.wind>60km/h': 'Strong wind',
    'weather.alert.temperature<5°c': 'Frost risk',
    'weather.advice.good': 'Weather is favorable for most farm activities.',
    'weather.advice.caution': 'Caution: Monitor conditions closely.',
    'weather.advice.danger': 'Danger: Take immediate action!',
    'weather.planningTip.gooddayforsowingorharvesting.': 'Good day for sowing or harvesting.',
    'weather.planningTip.applyfertilizerbeforerain.': 'Apply fertilizer before rain.',
    'weather.planningTip.avoidpesticidesprayingbeforerain.': 'Avoid pesticide spraying before rain.',
    'weather.planningTip.avoidsprayingorlighttasksduringstrongwinds.': 'Avoid spraying or light tasks during strong winds.',
    'weather.planningTip.planregularfarmactivities.': 'Plan regular farm activities.',
    'weather.howToRespond': 'How to respond to weather risks?',
    'weather.lastUpdated': 'Last updated',
    // Weather.tsx additions
    'weather.selectFarm': 'Select Farm',
    'weather.noFarmsAvailable': 'No farms available. Please add a farm to get started.',
    'weather.description.overcastClouds': 'overcast clouds',
    'weather.description.lightRain': 'light rain',
    'weather.description.clearSky': 'clear sky',
    'weather.description.fewClouds': 'few clouds',
    'weather.description.scatteredClouds': 'scattered clouds',
    'weather.description.brokenClouds': 'broken clouds',
    'weather.description.showerRain': 'shower rain',
    'weather.description.rain': 'rain',
    'weather.description.thunderstorm': 'thunderstorm',
    'weather.description.snow': 'snow',
    'weather.description.mist': 'mist',
    'weather.riskLevel.low': 'Low',
    'weather.riskLevel.moderate': 'Moderate',
    'weather.riskLevel.high': 'High',
    'weather.riskLevel.possible': 'Possible',
    'farm.myFarms': 'My Farms',
    'farm.manageDetails': 'Manage your farm locations and details',
    'farm.addFarm': 'Add Farm',
    'farm.searchFarms': 'Search farms...',
    'farm.status.good': 'Good',
    'farm.status.pending': 'Pending',
    'farm.status.needswater': 'Needs Water',
    'crops.tomato': 'Tomato',
    'crops.wheat': 'Wheat',
    'crops.cotton': 'Cotton',
  },
  ur: {
    // Navigation
    'nav.dashboard': 'ڈیش بورڈ',
    'nav.inventory': 'انوینٹری',
    'nav.pestControl': 'کیڑے مار کنٹرول',
    'nav.weather': 'موسم',
    'nav.market': 'مارکیٹ کی قیمتیں',
    'nav.education': 'تعلیم',
    'nav.aiInsights': 'AI بصیرت',
    'nav.farms': 'فارمز',
    'nav.contact': 'ہم سے رابطہ کریں',
    
    // Weather
    'weather.title': 'موسم کی پیش گوئی',
    'weather.searchPlaceholder': 'شہر کا نام درج کریں...',
    'weather.search': 'تلاش کریں',
    'weather.searchPrompt': 'موسم کی معلومات حاصل کرنے کے لیے شہر کا نام درج کریں',
    'weather.temperature': 'درجہ حرارت',
    'weather.feelsLike': 'محسوس ہونے والا درجہ حرارت',
    'weather.humidity': 'نمی',
    'weather.windSpeed': 'ہوا کی رفتار',
    'weather.details': 'موسم کی تفصیلات',
    'weather.condition': 'حالت',
    'weather.pressure': 'دباؤ',
    'weather.visibility': 'دکھائی',
    'weather.days.today': 'آج',
    'weather.days.tomorrow': 'کل',
    'weather.days.wednesday': 'بدھ',
    'weather.days.thursday': 'جمعرات',
    'weather.conditions.sunny': 'دھوپ',
    'weather.conditions.cloudy': 'ابر آلود',
    'weather.conditions.rain': 'بارش',
    'weather.conditions.windy': 'ہوا دار',
    
    // Market Prices
    'market.title': 'مارکیٹ کی قیمتیں',
    'market.todaysPrices': 'آج کی قیمتیں',
    'market.crops.wheat': 'گندم',
    'market.crops.rice': 'چاول',
    'market.crops.corn': 'مکئی',
    'market.crops.soybeans': 'سویابین',
    'market.regionTitle': 'علاقہ مخصوص فصل مارکیٹ ڈیٹا',
    'market.region.southasia': 'جنوبی ایشیا',
    'market.region.northamerica': 'شمالی امریکہ',
    'market.region.africa': 'افریقہ',
    'market.region.europe': 'یورپ',
    'market.region.southamerica': 'جنوبی امریکہ',
    'market.region.australia': 'آسٹریلیا',
    'market.region.eastasia': 'مشرقی ایشیا',
    'market.region.middleeast': 'مشرق وسطیٰ',
    'market.loading': 'لوڈ ہو رہا ہے...',
    'market.error': 'فصل کا ڈیٹا لوڈ نہیں ہو سکا۔',
    'market.cropIndexTable': 'فصل انڈیکس جدول',
    'market.crop': 'فصل',
    'market.type': 'قسم',
    'market.price': 'قیمت',
    'market.trend': 'رجحان',
    'market.change': 'تبدیلی',
    'market.cropName.rice': 'چاول',
    'market.cropName.wheat': 'گندم',
    'market.cropName.sugarcane': 'گنا',
    'market.cropName.cotton': 'کپاس',
    'market.cropName.maize': 'مکئی',
    'market.cropName.millets': 'باجرہ',
    'market.cropName.pulses': 'دالیں',
    'market.cropName.tea': 'چائے',
    'market.cropName.jute': 'جیوٹ',
    'market.cropName.barley': 'جو',
    'market.cropType.grain': 'اناج',
    'market.cropType.cashcrop': 'نقد آور فصل',
    'market.cropType.fiber': 'ریشہ',
    'market.cropType.legume': 'دالیں',
    'market.cropType.beverage': 'مشروب',
    'market.trend.up': 'اوپر',
    'market.trend.down': 'نیچے',
    'market.topCropsDistribution': 'سرفہرست 10 فصلوں کی تقسیم',
    'market.farmSuggestions': 'فارم کے مشورے',
    'market.suggestion.0': 'مٹی کی زرخیزی برقرار رکھنے کے لیے چاول اور گندم کی گردش کریں۔',
    'market.suggestion.1': 'مون سون کے موسم میں کیڑوں کی نگرانی کریں۔',
    'market.suggestion.2': 'گنے کے کھیتوں کے لیے ڈرپ آبپاشی پر غور کریں۔',
    'market.infoDisclaimer1': 'یہ معلومات',
    'market.infoDisclaimer2': 'AI سے تیار کردہ',
    'market.infoDisclaimer3': 'ہیں اور صرف رہنمائی کے لیے ہیں۔ یہ حقیقی وقت کی مارکیٹ ڈیٹا نہیں ہے۔',
    
    // Inventory
    'inventory.title': 'کیڑے مار دوائیوں کی انوینٹری',
    'inventory.addNewItem': 'نیا آئٹم شامل کریں',
    'inventory.searchPlaceholder': 'انوینٹری تلاش کریں...',
    'inventory.name': 'نام',
    'inventory.quantity': 'مقدار',
    'inventory.category': 'زمرہ',
    'inventory.expiryDate': 'میعاد ختم ہونے کی تاریخ',
    'inventory.actions': 'کارروائیاں',
    'inventory.unit': 'یونٹ',
    'inventory.cancel': 'منسوخ کریں',
    'inventory.addItem': 'آئٹم شامل کریں',
    'inventory.categories.organic': 'نامیاتی',
    'inventory.categories.chemical': 'کیمیائی',
    'inventory.units.liters': 'لیٹر',
    'inventory.units.kg': 'کلوگرام',
    'inventory.units.units': 'یونٹس',
    'inventory.supplier': 'سپلائر',
    'inventory.purchaseDate': 'خریدنے کی تاریخ',
    'inventory.notes': 'نوٹس',
    'inventory.editItem': 'آئٹم میں ترمیم کریں',
    'inventory.updateItem': 'آئٹم اپ ڈیٹ کریں',
    'inventory.deleteItem': 'آئٹم حذف کریں',
    'inventory.delete': 'حذف کریں',
    'inventory.deleteConfirmation': 'کیا آپ واقعی {{name}} کو حذف کرنا چاہتے ہیں؟',
    'inventory.lowStockAlert': 'کم اسٹاک انتباہ',
    'inventory.lowStockItems': '{{count}} آئٹمز کا اسٹاک کم ہو رہا ہے',
    'inventory.expiringAlert': 'میعاد ختم ہونے والے آئٹمز کا انتباہ',
    'inventory.expiringItems': '{{count}} آئٹمز کی میعاد ختم ہو رہی ہے',
    'inventory.totalItems': 'کل آئٹمز',
    'inventory.organicItems': 'نامیاتی آئٹمز',
    'inventory.chemicalItems': 'کیمیائی آئٹمز',
    
    // Education
    'education.title': 'تعلیم اور وسائل',
    'education.articlesGuides': 'مضامین اور رہنما',
    'education.videosTutorials': 'ویڈیوز اور ٹیوٹوریلز',
    'education.regulatoryUpdates': 'قانونی اپ ڈیٹس',
    'education.tipsFarming': 'بہتر کاشتکاری کے مشورے',
    'education.faqsHelp': 'عمومی سوالات اور مدد',
    'education.pdfDownloads': 'پی ڈی ایف ڈاؤن لوڈز / کتابچے',
    'education.glossary': 'اصطلاحات / لغت',
    'education.article.0': 'محفوظ کیڑے مار ادویات کا استعمال اور ذخیرہ',
    'education.article.1': 'صحیح کیڑے مار دوا کا انتخاب کیسے کریں',
    'education.article.2': 'کیڑے مار ادویات کے زیادہ یا غلط استعمال کے اثرات',
    'education.article.3': 'نامیاتی اور ماحول دوست متبادل',
    'education.article.4': 'حکومتی قوانین اور قانونی استعمال',
    'education.video.0': 'کیسے کریں: محفوظ کیڑے مار دوا کا استعمال',
    'education.video.1': 'فصل کے لحاظ سے کیڑوں کا کنٹرول',
    'education.video.2': 'آلات کی صفائی اور دیکھ بھال',
    'education.video.3': 'حقیقی کسانوں کے تجربات',
    'education.tip.0': 'ہمیشہ لیبل کی ہدایات پڑھیں اور ان پر عمل کریں۔',
    'education.tip.1': 'کیڑے مار ادویات کو تبدیل کریں تاکہ کیڑوں میں مزاحمت نہ ہو۔',
    'education.tip.2': 'کیمیکلز کو سنبھالتے وقت حفاظتی سامان استعمال کریں۔',
    'education.tip.3': 'پولینیٹرز کو نقصان سے بچانے کے لیے صبح یا شام سپرے کریں۔',
    'education.tip.4': 'تمام سپرے کی تفصیلات ریکارڈ میں رکھیں۔',
    'education.tip.5': 'کیڑے مار ادویات کو بچوں اور جانوروں سے دور، ٹھنڈی اور خشک جگہ پر رکھیں۔',
    'education.tip.6': 'کیمیکل کے استعمال کو کم کرنے کے لیے IPM طریقے اپنائیں۔',
    'education.tip.7': 'ہر استعمال کے بعد آلات کو اچھی طرح صاف کریں۔',
    'education.faq.0.q': 'اگر کیڑے مار دوا جلد پر گر جائے تو کیا کریں؟',
    'education.faq.0.a': 'آلودہ کپڑے اتاریں اور جلد کو صابن اور پانی سے اچھی طرح دھوئیں۔ جلن برقرار رہے تو ڈاکٹر سے رجوع کریں۔',
    'education.faq.1.q': 'کیسے معلوم ہو کہ کیڑے مار دوا فصل کے لیے محفوظ ہے؟',
    'education.faq.1.a': 'لیبل پر منظور شدہ فصلیں دیکھیں اور مقامی زرعی ماہرین سے مشورہ کریں۔',
    'education.faq.2.q': 'REI (ری-انٹری انٹرول) کیا ہے؟',
    'education.faq.2.a': 'REI وہ کم از کم وقت ہے جس کے بعد سپرے شدہ کھیت میں دوبارہ داخل ہو سکتے ہیں۔',
    'education.faq.3.q': 'سپرے کے بعد فصل جل جائے تو کیا کریں؟',
    'education.faq.3.a': 'پروڈکٹ کا استعمال بند کریں، اگر ممکن ہو تو کھیت کو پانی دیں اور ماہر سے مشورہ کریں۔',
    'education.glossary.0.term': 'ہر بی سائیڈ',
    'education.glossary.0.def': 'گھاس مار دوا',
    'education.glossary.1.term': 'فنجی سائیڈ',
    'education.glossary.1.def': 'فنگس کنٹرول کرنے والی دوا',
    'education.glossary.2.term': 'باقی اثر',
    'education.glossary.2.def': 'سپرے کے بعد دوا کتنے عرصے تک فعال رہتی ہے',
    'education.glossary.3.term': 'IPM',
    'education.glossary.3.def': 'متکمل کیڑوں کا انتظام، ایک جامع طریقہ',
    'education.glossary.4.term': 'REI',
    'education.glossary.4.def': 'ری-انٹری انٹرول، سپرے کے بعد دوبارہ داخلے کا وقت',
    'education.regulation.0': 'زرعی محکموں کے نئے قوانین',
    'education.regulation.1': 'پاکستان میں ممنوعہ کیڑے مار ادویات (2024)',
    'education.regulation.1.detail.0': 'الڈرین',
    'education.regulation.1.detail.1': 'کلورڈین',
    'education.regulation.1.detail.2': 'ڈی ڈی ٹی',
    'education.regulation.1.detail.3': 'ڈائیلڈرین',
    'education.regulation.1.detail.4': 'اینڈرین',
    'education.regulation.1.detail.5': 'ہیپٹا کلور',
    'education.regulation.1.detail.6': 'لنڈین',
    'education.regulation.1.detail.7': 'میرکس',
    'education.regulation.1.detail.8': 'ٹوکسا فین',
    'education.regulation.2': 'منظور شدہ کیڑے مار ادویات (2024)',
    'education.regulation.2.detail.0': 'امیڈا کلوپرڈ',
    'education.regulation.2.detail.1': 'لمبڈا سائی ہالو تھرین',
    'education.regulation.2.detail.2': 'کاربینڈازم',
    'education.regulation.2.detail.3': 'مینکوزیب',
    'education.regulation.2.detail.4': 'گلیفوسیٹ',
    'education.pdf.0': 'فصل کے لحاظ سے کیڑے مار دوا کا چارٹ',
    'education.pdf.1': 'موسم کے مطابق سپرے شیڈول',
    'education.pdf.2': 'بیماری کی شناخت اور علاج کا دستی',
    
    // Pest Control
    'pestControl.title': 'کیڑے مار کنٹرول مینجمنٹ',
    'pestControl.currentThreats': 'موجودہ خطرات',
    'pestControl.aphidsDetected': 'جھینگر کا پتہ چلا',
    'pestControl.highRiskSectorA': 'سیکٹر A میں زیادہ خطرہ',
    'pestControl.takeAction': 'کارروائی کریں',
    'pestControl.protectedAreas': 'محفوظ علاقے',
    'pestControl.sectorB': 'سیکٹر B',
    'pestControl.treatmentSuccess': 'علاج کامیابی سے لاگو کیا گیا',
    
    // AI Dashboard
    'ai.title': 'AI بصیرت ڈیش بورڈ',
    'ai.pestDetection': 'کیڑوں کی شناخت',
    'ai.yieldPrediction': 'پیداوار کی پیش گوئی',
    'ai.weatherAnalysis': 'موسم کا تجزیہ',
    'ai.marketPrediction': 'مارکیٹ کی قیمت کی پیش گوئی',
    'ai.uploadImage': 'تصویر اپ لوڈ کریں',
    'ai.detectedPests': 'پائے گئے کیڑے',
    'ai.confidence': 'اعتماد',
    'ai.loading': 'لوڈ ہو رہا ہے...',
    
    // Common
    'common.historical': 'تاریخی',
    'common.predicted': 'پیش گوئی',
    'common.farmer': 'کسان جان',
    'common.viewProfile': 'پروفائل دیکھیں',
    'common.temperature': 'درجہ حرارت',
    'common.humidity': 'نمی',
    'common.windSpeed': 'ہوا کی رفتار',
    'common.soilMoisture': 'مٹی کی نمی',
    'common.alerts': 'حالیہ انتباہات',
    'common.farmHealth': 'فارم کی صحت کا جائزہ',
    'common.cropHealth': 'فصل کی صحت کا انڈیکس',
    'common.pestRisk': 'کیڑوں کا خطرہ',
    'common.waterUsage': 'پانی کا استعمال',
    'common.soilQuality': 'مٹی کی معیار',
    'login.title': 'اپنے اکاؤنٹ میں سائن ان کریں',
    'login.subtitle': 'خوش آمدید! براہ کرم اپنی تفصیلات درج کریں۔',
    'login.email': 'ای میل ایڈریس',
    'login.emailPlaceholder': 'ای میل ایڈریس',
    'login.password': 'پاس ورڈ',
    'login.passwordPlaceholder': 'پاس ورڈ',
    'login.button': 'سائن ان کریں',
    'register.title': 'اپنا اکاؤنٹ بنائیں',
    'register.subtitle': 'ہمارے ساتھ شامل ہوں اور اپنا سفر شروع کریں!',
    'register.name': 'پورا نام',
    'register.namePlaceholder': 'پورا نام',
    'register.email': 'ای میل ایڈریس',
    'register.emailPlaceholder': 'ای میل ایڈریس',
    'register.password': 'پاس ورڈ',
    'register.passwordPlaceholder': 'پاس ورڈ',
    'register.button': 'رجسٹر کریں',
    'dashboard.title': 'ڈیش بورڈ',
    'dashboard.subtitle': 'اپنے فارم کی صحت کی نگرانی اور انتظام کریں',
    'dashboard.lastUpdated': 'آخری تازہ کاری: 5 منٹ پہلے',
    'dashboard.activities': 'فارم کی سرگرمیاں',
    'dashboard.addActivity': 'سرگرمی شامل کریں',
    'dashboard.sortByDate': 'تاریخ کے لحاظ سے ترتیب دیں',
    'dashboard.sortByPriority': 'ترجیح کے لحاظ سے ترتیب دیں',
    'dashboard.sortByStatus': 'حیثیت کے لحاظ سے ترتیب دیں',
    'dashboard.allActivities': 'تمام سرگرمیاں',
    'dashboard.pendingActivities': 'زیر التواء سرگرمیاں',
    'dashboard.completedActivities': 'مکمل سرگرمیاں',
    'dashboard.allTypes': 'تمام اقسام',
    'dashboard.tasks': 'کام',
    'dashboard.recommendations': 'تجاویز',
    'dashboard.activityTitle': 'سرگرمی کا عنوان',
    'dashboard.activityDescription': 'سرگرمی کی تفصیل',
    'dashboard.task': 'کام',
    'dashboard.recommendation': 'تجویز',
    'dashboard.lowPriority': 'کم ترجیح',
    'dashboard.mediumPriority': 'درمیانی ترجیح',
    'dashboard.highPriority': 'زیادہ ترجیح',
    'dashboard.dueDate': 'آخری تاریخ',
    'dashboard.cancel': 'منسوخ کریں',
    'dashboard.updateActivity': 'سرگرمی اپ ڈیٹ کریں',
    'dashboard.priorityLow': 'کم ترجیح',
    'dashboard.priorityMedium': 'درمیانی ترجیح',
    'dashboard.priorityHigh': 'زیادہ ترجیح',
    'dashboard.due': 'آخری تاریخ',
    'dashboard.editActivity': 'سرگرمی میں ترمیم کریں',
    'dashboard.deleteActivity': 'سرگرمی حذف کریں',
    'dashboard.taskSoilTesting': 'مٹی کی جانچ ضروری ہے',
    'dashboard.descSoilTesting': 'شمالی کھیت میں مٹی کی جانچ کریں تاکہ غذائی اجزاء اور پی ایچ بیلنس چیک کیا جا سکے',
    'dashboard.taskIrrigation': 'آبپاشی کے نظام کی دیکھ بھال',
    'dashboard.descIrrigation': 'جنوبی کھیت میں آبپاشی کے نظام کا معائنہ اور دیکھ بھال کریں، لیکس اور پریشر کے مسائل چیک کریں',
    'dashboard.taskCropRotation': 'فصل کی گردش کی سفارش',
    'dashboard.descCropRotation': 'مٹی کے تجزیہ کی بنیاد پر، مشرقی کھیت میں فصلوں کی گردش پر غور کریں تاکہ مٹی کی صحت بہتر ہو سکے',
    'farm.editFarm': 'فارم میں ترمیم کریں',
    'farm.deleteFarm': 'فارم حذف کریں',
    'farm.size': 'رقبہ',
    'farm.acres': 'ایکڑ',
    'farm.activities': 'سرگرمیاں',
    'farm.pesticideUsage': 'کیڑے مار ادویات کا استعمال',
    'farm.totalUsed': 'کل استعمال',
    'farm.lastUsed': 'آخری استعمال',
    'farm.addActivity': 'سرگرمی شامل کریں',
    'farm.area': 'رقبہ',
    'farm.good': 'اچھی',
    'farm.health': 'صحت',
    'farm.watered': 'پانی دیا گیا',
    'farm.pending': 'زیر التواء',
    'farm.needsWater': 'پانی کی ضرورت',
    'farm.recentActivities': 'حالیہ سرگرمیاں',
    'farm.pesticidesList': 'ادویات کی فہرست',
    'crops.wheat': 'گندم',
    'crops.cotton': 'کپاس',
    'crops.tomato': 'ٹماٹر',
    // Contact Us
    'contact.heading': 'ہم سے رابطہ کریں',
    'contact.subheading': 'ہم آپ کی رائے کے منتظر ہیں! نیچے فارم پُر کریں اور ہماری ٹیم جلد آپ سے رابطہ کرے گی۔',
    'contact.name': 'نام',
    'contact.namePlaceholder': 'آپ کا نام',
    'contact.email': 'ای میل',
    'contact.emailPlaceholder': 'آپ کا ای میل',
    'contact.message': 'پیغام',
    'contact.messagePlaceholder': 'اپنا پیغام لکھیں...',
    'contact.sendButton': 'پیغام بھیجیں',
    'contact.orReachUs': 'یا ہم سے یہاں رابطہ کریں:',
    'contact.address': '123 گرین ویلی، فارم سٹی، ملک',
    'contact.linkedin': 'لنکڈ اِن',
    'contact.facebook': 'فیس بک',
    'contact.twitter': 'ٹوئٹر',
    'contact.instagram': 'انسٹاگرام',
    // Sidebar
    'sidebar.logo': 'اگرو اے آئی',
    'sidebar.logout': 'لاگ آؤٹ',
    'sidebar.urdu': 'اردو',
    'sidebar.english': 'انگریزی',
    // Navbar
    'navbar.logo': 'اگرو اے آئی',
    // WeatherForecast additions
    'weather.searchFarmPlaceholder': 'فارم تلاش کریں (نام، شہر، یا علاقہ)...',
    'weather.noFarmsFound': 'کوئی فارم نہیں ملا',
    'weather.addFarmsPrompt': 'موسم کا ڈیٹا دیکھنے کے لیے فارم شامل کریں۔',
    'weather.rain': 'بارش',
    'weather.frostRisk': 'فراسٹ کا خطرہ',
    'weather.hailstorm': 'ژالہ باری',
    'weather.risks': 'خطرات',
    'weather.risk.flooding': 'سیلاب',
    'weather.risk.drought': 'قحط',
    'weather.risk.cropdamagefromfrost': 'فراسٹ سے فصل کو نقصان',
    'weather.risk.cropdamagefromheatwave': 'گرمی کی لہر سے فصل کو نقصان',
    'weather.risk.lodging/structuredamage': 'ڈھانچے کو نقصان',
    'weather.risk.diseasespread': 'بیماری کا پھیلاؤ',
    'weather.alert.rain>50mm': 'تیز بارش',
    'weather.alert.wind>60km/h': 'تیز ہوا',
    'weather.alert.temperature<5°c': 'فراسٹ کا خطرہ',
    'weather.advice.good': 'زیادہ تر زرعی سرگرمیوں کے لیے موسم سازگار ہے۔',
    'weather.advice.caution': 'احتیاط: حالات پر نظر رکھیں۔',
    'weather.advice.danger': 'خطرہ: فوری کارروائی کریں!',
    'weather.planningTip.gooddayforsowingorharvesting.': 'بوائی یا کٹائی کے لیے اچھا دن ہے۔',
    'weather.planningTip.applyfertilizerbeforerain.': 'بارش سے پہلے کھاد ڈالیں۔',
    'weather.planningTip.avoidpesticidesprayingbeforerain.': 'بارش سے پہلے کیڑے مار دوا کا چھڑکاؤ نہ کریں۔',
    'weather.planningTip.avoidsprayingorlighttasksduringstrongwinds.': 'تیز ہوا میں چھڑکاؤ یا ہلکے کام سے گریز کریں۔',
    'weather.planningTip.planregularfarmactivities.': 'معمول کی زرعی سرگرمیاں انجام دیں۔',
    'weather.howToRespond': 'موسمی خطرات سے کیسے نمٹا جائے؟',
    'weather.lastUpdated': 'آخری تازہ کاری',
    // Weather.tsx additions
    'weather.selectFarm': 'فارم منتخب کریں',
    'weather.noFarmsAvailable': 'کوئی فارم دستیاب نہیں۔ براہ کرم شروع کرنے کے لیے فارم شامل کریں۔',
    'weather.description.overcastClouds': 'ابر آلود بادل',
    'weather.description.lightRain': 'ہلکی بارش',
    'weather.description.clearSky': 'صاف آسمان',
    'weather.description.fewClouds': 'کچھ بادل',
    'weather.description.scatteredClouds': 'چھٹے ہوئے بادل',
    'weather.description.brokenClouds': 'ٹوٹے ہوئے بادل',
    'weather.description.showerRain': 'بارش',
    'weather.description.rain': 'بارش',
    'weather.description.thunderstorm': 'گرج چمک',
    'weather.description.snow': 'برفباری',
    'weather.description.mist': 'دھند',
    'weather.riskLevel.low': 'کم',
    'weather.riskLevel.moderate': 'درمیانہ',
    'weather.riskLevel.high': 'زیادہ',
    'weather.riskLevel.possible': 'ممکن',
    'farm.myFarms': 'میرے فارم',
    'farm.manageDetails': 'اپنے فارم کے مقامات اور تفصیلات کا انتظام کریں',
    'farm.addFarm': 'نیا فارم شامل کریں',
    'farm.searchFarms': 'فارم تلاش کریں...',
    'farm.status.good': 'Good',
    'farm.status.pending': 'Pending',
    'farm.status.needswater': 'Needs Water',
    'crops.tomato': 'ٹماٹر',
    'crops.wheat': 'گندم',
    'crops.cotton': 'کپاس',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 